# Generated by Django 3.1.1 on 2020-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200911_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
