# Generated by Django 3.1.1 on 2020-09-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200911_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo_main',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
    ]
