# Generated by Django 3.1.1 on 2020-09-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200911_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='export_csv',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
